# Generated by Django 4.0.6 on 2023-10-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='viewsTime',
            field=models.IntegerField(default=1),
        ),
    ]
