# Generated by Django 4.0.6 on 2023-10-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_viewstime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='viewsTime',
            field=models.IntegerField(default=0),
        ),
    ]
